resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts

pr: 
  branches:
    include:
    - master
  paths:
    exclude:
    - terraform/10-video-hearing-wowza/*

pool: 
  vmImage: ubuntu-22.04

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - terraform/10-video-hearing-wowza/*

parameters:
  - name: environment
    type: object
    default:
    - name: Dev
      dependsOnEnv: ""
    - name: Demo
      dependsOnEnv: "Dev"
    - name: ITHC
      dependsOnEnv: "Dev"
    - name: Stg
      dependsOnEnv: "Dev"
    - name: Test
      dependsOnEnv: "Dev"
    - name: Prod
      dependsOnEnv: "Stg"

variables:
- name: tfVersion
  value: 1.3.7
- group: external
- name: azureLocation
  value: 'UK South'
stages:

################################################
# Validate Infra Code. #########################

- stage: Validate_Terraform_Code
  displayName: 'Validate Terraform Code'
  jobs:
    - job: Validate_Terraform_Code
      displayName: Validate Terraform Code
      steps:
        - template: pipeline-steps/terraform-validate.yaml
          parameters:
            tfversion: ${{ variables.tfversion }}


################################################
# Terraform Plan & Apply. ######################

- ${{ each env in parameters.environment }}:
  - template: pipeline-steps/terraform-plan-apply.yaml
    parameters:
      terraformVersion: ${{ variables.tfVersion }}
      env: ${{ env.name }}
      location: ${{ variables.azureLocation }}
      environmentServiceConnection: DTS-SHAREDSERVICES-${{ env.name }}-Video Hearings
      product: vh
      activityName: Video_Hearing_Core
      tfStateResourceGroup: vh-infra-core-${{ env.name }}-tf
      tfStateStorageAccountName: vhinfracore${{ env.name }}tf
      dependsOnEnv: ${{ env.dependsOnEnv }}
