resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: master 
      endpoint: hmcts

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: environment
  type: string
  values:
  - 'ITHC'
  - 'Test'
  - 'Demo'

variables:
- name: tfVersion
  value: 1.3.7
- name: azureLocation
  value: 'UK South'
- group: external

################################################
# Terraform Plan & Destroy. ####################
stages:
  - template: pipeline-steps/terraform-plan-apply.yaml
    parameters:
      terraformVersion: ${{ variables.tfVersion }}
      env: ${{ parameters.environment }}
      location: ${{ variables.azureLocation }}
      environmentServiceConnection: DTS-SHAREDSERVICES-${{ parameters.environment }}-Video Hearings
      product: vh
      activityName: Video_Hearing_Core
      tfStateResourceGroup: vh-infra-core-${{ parameters.environment }}-tf
      tfStateStorageAccountName: vhinfracore${{ parameters.environment }}tf
      dependsonEnv: '[]'
      destroyInfra: true