resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: master 
      endpoint: hmcts

trigger: none

parameters:
  - name: environment
    displayName: env to run against...
    type: string
    values:
    - dev
    - stg
    - test
    - ithc
    - demo
    - prod

    # The other option is you have a param for each database with a yes/no option, but that will be messy. THe object also lets us loop
  - name: databases
    displayName: list the required databases to backup
    type: object
    default:
    - vhnotification
    - vhbookings
    - vhvideo

# Use variables to peice together strings based on your params this can be done as they are set at run time
variables:
  - name: server
    value: "vh-infra-core-${{ parameters.environment }}"

  - name: sa
    value: "vhinfracore${{ parameters.environment }}"

  - name: keyvault
    value: "vh-infra-core-${{ parameters.environment }}"

jobs:
  - job: prepare_target_storage
    displayName: 'Prepare Target Storage for Backups'
    ${{ if or(eq(parameters.environment, 'Stg'), eq(parameters.environment, 'Prod')) }}:
      steps:
        - template: templates/Azure/Common/unlock-lock.yaml@templates
          parameters:
            addOrDelete: delete
            azureSubscription: 'DTS-SHAREDSERVICES-${{parameters.environment}}-Video Hearings'
            lockName: ${{ parameters.environment }}-lock
            resourceGroup: vh-infra-core-${{ parameters.environment }}

        - task: AzurePowerShell@5
          displayName: 'Get Service Principal Details'
          inputs:
            azureSubscription: 'DTS-SHAREDSERVICES-${{parameters.environment}}-Video Hearings'
            ScriptType: 'InlineScript'
            Inline: |
              $Context = Get-AzContext
              $AzureDevOpsServicePrincipal = Get-AzADServicePrincipal -ApplicationId $Context.Account.Id
              $ObjectId = $AzureDevOpsServicePrincipal.Id

              echo "##vso[task.setvariable variable=oid]$ObjectId"
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true 

        - task: AzureCLI@2
          displayName: 'Create Backups Key Vault'
          inputs:
            azureSubscription: 'DTS-SHAREDSERVICES-${{parameters.environment}}-Video Hearings'
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              echo "Fetching SQL credentials from Infra Core Key Vault..."
              $username = az keyvault secret show --vault-name vh-infra-core-${{parameters.environment}} -n db-admin-username -o tsv --query "value"
              $password = az keyvault secret show --vault-name vh-infra-core-${{parameters.environment}} -n db-admin-password -o tsv --query "value"
              $resourceGroup = "vh-infra-core-backups-${{ parameters.environment }}"
              $keyVaultName = "vh-infra-core-backups-${{ parameters.environment }}"
              $location = "uksouth"
              echo "Creating Key Vault $keyVaultName in $resourceGroup"
              az keyvault create --name $keyVaultName --resource-group $resourceGroup --location $location
              echo "Adding SQL credentials to Key Vault $keyVaultName"
              az keyvault secret set --vault-name $keyVaultName --name db-admin-username --value $username
              az keyvault secret set --vault-name $keyVaultName --name db-admin-password --value $password

        - task: AzureCLI@2
          displayName: 'Create Backups Resource Group'
          inputs:
            azureSubscription: 'DTS-SHAREDSERVICES-${{parameters.environment}}-Video Hearings'
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              $resourceGroup="vh-infra-core-backups-${{ parameters.environment }}"  
              $storageAccountName="vhinfracorebackups${{ parameters.environment }}"
              $containerName="db-backup"
              $location="uksouth"
              switch -Wildcard ($resourceGroup)
              {
                '*dev*'  { $envTag = "development"}
                '*prod*' { $envTag = "production"}
                '*stg*'  { $envTag = "staging"}
                '*ithc*' { $envTag = "ITHC"}
                '*test*' { $envTag = "testing"}
                '*sbox*' { $envTag = "sandbox"}
                '*demo*' { $envTag = "demo"}
              }

              echo "Creating Resource Group $resourceGroup"
              $tags=@("application=video-hearings-service", "builtFrom=hmcts/vh-shared-infrastructure", "businessArea=Cross-Cutting", "criticality=High", "environment=$envTag")
              echo "Tags: $tags"
              az group create --name $resourceGroup --location $location --tags $tags
              echo "Creating Backups Storage $storageAccountName"
              az storage account create --name $storageAccountName --resource-group $resourceGroup --location $location --kind "StorageV2" --allow-blob-public-access "false" --tags $tags --sku "Standard_LRS" --min-tls-version "TLS1_2"
                                        
              az storage container create --name $containerName --account-name $storageAccountName --auth-mode "login"
              echo "Setting permissions for group to access Storage Account"
              $groupName = "DTS VH Wowza Storage Blob Data Reader (env:${{ parameters.environment }})"
              $groupId = az ad group show --group "$groupName" --query id -o tsv
              $storageAccountId = az storage account show --name $storageAccountName --resource-group $resourceGroup --query id -o tsv
              az role assignment create --assignee-object-id $groupId --assignee-principal-type Group --role "Storage Blob Data Contributor" --scope $storageAccountId

  # - ${{each database in parameters.databases}}:
  #   - job: backup_${{database}}
  #     dependsOn: prepare_target_storage
  #     displayName: 'Backup ${{database}} Database'
  #     steps:
  #       - task: AzureCLI@2
  #         inputs:
  #           azureSubscription: 'DTS-SHAREDSERVICES-${{parameters.environment}}-Video Hearings'
  #           scriptType: 'pscore'
  #           scriptLocation: 'inlineScript'
  #           inlineScript: |
  #             echo "Fetching SQL credentials from Key Vault..."
  #             $username = az keyvault secret show --vault-name vh-infra-core-${{parameters.environment}} -n db-admin-username -o tsv --query "value"
  #             $password = az keyvault secret show --vault-name vh-infra-core-${{parameters.environment}} -n db-admin-password -o tsv --query "value"
  #             echo "Fetching Storage Account Key..."
  #             $key=$(az storage account keys list -n vhinfracorebackups${{ parameters.environment }} --resource-group vh-infra-core-backups-${{parameters.environment}}  -o tsv --query "[0].value")
  #             $date = get-date -format "yyyy-MM-dd_hhmmss"
  #             $uri = "https://vhinfracorebackups${{parameters.environment}}.blob.core.windows.net/db-backup/${{database}}-$date.bacpac"
  #             echo "Creating SQL Server Firewall Rule to allow Azure services..."
  #             az sql server firewall-rule create -g vh-infra-core-${{parameters.environment}} -s vh-infra-core-${{parameters.environment}} -n "allow-azure-services" --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
  #             echo "Exporting ${{database}} database to $uri..."
  #             az sql db export -p $password --admin-user $username --storage-key $key --storage-key-type StorageAccessKey --storage-uri $uri --name ${{database}} -g vh-infra-core-${{parameters.environment}} --server vh-infra-core-${{parameters.environment}}
  #             echo "Deleting SQL Server Firewall Rule..."
  #             az sql server firewall-rule delete -g vh-infra-core-${{parameters.environment}} -s vh-infra-core-${{parameters.environment}} -n "allow-azure-services"