name: VH Shared Services AKS Azure Infrastructure Nightly Drift Check Pipeline
trigger:
  - none

pr:
  - none

schedules:
- cron: "0 21 * * 1,2,3,4,5"
  displayName: Nightly
  branches:
    include:
    - master
  always: true
- cron: "0 21 1 * *"
  displayName: Monthly
  branches:
    include:
    - master
  always: true


resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts
      
parameters:

  - name: location
    displayName: Location
    type: string
    default: 'UK South'
    values:
    - 'UK South'
    - 'UK West'

  - name: env
    displayName: Environment
    type: object
    values: []
    default: ['DEV', ITHC, DEMO, TEST, STG]
    #default: ['SBOX']

variables:
  - name: tfversion
    value: 1.1.0
  # If another project comes along and wants to use the same pipeline file then make this a variable in the UI
  # but it might be better to template the pipeline more and have a different pipeline file
  # so that someone doesn't pick the wrong var in the dropdown
  - name: project
    value: application
  # same comment as above ^^
  - name: location
    value: 'UK South'

stages:
  - ${{each environment in parameters.env}}:

    - stage: Video_Hearing_Core_${{environment}}
      displayName: 'Video_Hearing_Core${{environment}}'
      dependsOn: []
      jobs:
        - job: Video_Hearing_Core_${{environment}}
          pool:
            vmImage: 'Ubuntu 18.04'
          variables:
            - name: serviceConnection
              value: DTS-SHAREDSERVICES-${{ environment }}-Video Hearings
            - group: vh-tenant-creds
            - group: vh-alerting-Logic-App-Details
          steps:
            - template: pipeline-steps/vh-tenant-replacement.yaml
              parameters:
                vh_tenant_id: $(vh_tenant_id)
                vh_client_secret: $(vh_client_secret)
                vh_client_id: $(vh_client_id)
                environment: ${{ environment }}

            - template: pipeline-steps/tfplan-drift-check.yaml
              parameters:
                environment: ${{ environment }}
                location: ${{ parameters.location }}
                stack: '09-video-hearing-core'
                project: $(project)
                product: 'vh'
                builtFrom: $(Build.Repository.Name)
                tfversion: $(tfversion)
                serviceConnection:  ${{variables.serviceConnection}}
                activity_name: Video_Hearing_Core
                run_stage: ${{ parameters.Run_Stage }}
                state_sub: $(vh_tf_state_sub)
                logicAppUrl: $(vh-logic-app-url)

    - stage: Video_Hearing_Wowza_${{environment}}
      displayName: 'Video_Hearing_Wowza_${{environment}}'
      dependsOn: []
      jobs:
        - job: Video_Hearing_Wowza_${{environment}}
          pool:
            vmImage: 'Ubuntu 18.04'
          variables:
            - name: serviceConnection
              value: DTS-SHAREDSERVICES-${{ environment }}-Video Hearings
            - group: vh-tenant-creds
            - group: vh-alerting-Logic-App-Details
          steps:
            - template: pipeline-steps/sshkey-download.yaml
            - template: pipeline-steps/tfplan-drift-check.yaml
              parameters:
                environment: ${{ environment }}
                location: ${{ parameters.location }}
                stack: '10-video-hearing-wowza'
                project: $(project)
                product: 'wowza'
                builtFrom: $(Build.Repository.Name)
                tfversion: $(tfversion)
                serviceConnection: ${{variables.serviceConnection}}
                activity_name: Video_Hearing_Wowza
                run_stage: ${{ parameters.Run_Stage }}
                state_sub: $(vh_tf_state_sub)
                logicAppUrl: $(vh-logic-app-url)