variables:
  dynatrace_host_group: "SDS_VH_PROD"
  dynatrace_tenant_id: "ebe20728"
  env_long: "production"
  dynatrace_token_secret_name: 'dynatrace-prod-api-key'
  central_infra_kv: 'infra-vault-prod'