parameters:
- name: env
  type: string

- name: terraformVersion
  type: string
  default: 1.1.0

- name: location
  type: string
  default: 'UK South'
  values:
    - UK South
    - UK West

- name: project
  type: string
  default: application

- name: environmentServiceConnection
  type: string

- name: stack
  type: string
  values:
    - 09-video-hearing-core
    - 10-video-hearing-wowza

- name: product
  type: string
  values:
    - vh
    - wowza

- name: activityName
  type: string
  values:
    - Video_Hearing_Wowza
    - Video_Hearing_Core

- name: tfStateResourceGroup
  type: string

- name: tfStateStorageAccountName 
  type: string


stages:
- stage: 'Terraform_Plan_${{ parameters.env }}'
  displayName: 'Terraform Plan ${{ parameters.env }}'
  variables:
    - template: ../config\pipeline\vars\${{ lower(parameters.product) }}/common.yaml
    - template: ../config\pipeline\vars\${{ lower(parameters.product) }}/${{ lower(parameters.env) }}.yaml
  jobs: 
    - job: 'Terraform_Plan_${{ parameters.env }}'
      displayName: 'Terraform Plan ${{ parameters.env }}'
      variables:
      - name: environment
        value: ${{ parameters.env }}
      - group: vh-tenant-creds
      - template: ado-vars.yaml
        parameters:
          environment: ${{ parameters.env }}
        # If another project comes along and wants to use the same pipeline file then make this a variable in the UI
        # but it might be better to template the pipeline more and have a different pipeline file
        # so that someone doesn't pick the wrong var in the dropdown
        # same comment as above ^^
      steps:
      - ${{ if eq(parameters.activityName, 'Video_Hearing_Core') }}:
        - template: vh-tenant-replacement.yaml
          parameters:
            environment: ${{ variables.environment }}

        - template: ado-vars-to-tf.yaml
          parameters: 
            environment: ${{ variables.environment }}

      - template: templates\Azure\Common\unlock-resource-group.yml@templates
        parameters:
          subscriptionName: ${{parameters.environmentServiceConnection}}
          ${{ if eq(parameters.activityName, 'Video_Hearing_Wowza') }}:
            resourceGroupName: "vh-infra-wowza-${{variables.environment}}"
          ${{ else }}:
            resourceGroupName: "vh-infra-core-${{variables.environment}}" 
          lockName: "${{variables.environment}}-lock"

      - template: terraform-plan.yaml
        parameters:
          environment: ${{ variables.environment }}
          location: ${{ parameters.location }}
          stack: ${{ parameters.stack }}
          project: ${{ parameters.project }}
          product: ${{ parameters.product }}
          builtFrom: $(Build.Repository.Name)
          tfversion: ${{ parameters.terraformVersion }}
          serviceConnection: ${{ parameters.environmentServiceConnection }}
          tfStateResourceGroup: ${{ lower(parameters.tfStateResourceGroup) }}
          tfStateStorageAccountName: ${{ lower(parameters.tfStateStorageAccountName) }}
          activity_name: ${{ parameters.activityName  }}
          ${{ if eq(parameters.activityName, 'Video_Hearing_Core') }}:
            additional_tf_var: $(ado_vars_to_tf.ado_vars)

################################################
# Terraform Apply Dev. #########################

- stage: 'Terraform_Apply_${{ parameters.env }}'
  displayName: 'Terraform Apply ${{ parameters.env }}'
  variables:
    - name: environment
      value: ${{ parameters.env }}
    - group: vh-tenant-creds
    - template: ado-vars.yaml
      parameters:
        environment: ${{ parameters.env }}
      # If another project comes along and wants to use the same pipeline file then make this a variable in the UI
      # but it might be better to template the pipeline more and have a different pipeline file
      # so that someone doesn't pick the wrong var in the dropdown
    # same comment as above ^^
    
    - template: ../config\pipeline\vars\${{ lower(parameters.product) }}/common.yaml
    - template: ../config\pipeline\vars\${{ lower(parameters.product) }}/${{ lower(parameters.env) }}.yaml
  jobs:
    - deployment: 'Terraform_Apply_${{ parameters.env }}'
      displayName: Terraform Apply ${{ parameters.env }}
      continueOnError: false
      environment: ${{ parameters.env }}
      strategy:
        runOnce:
          deploy:
            steps:

            - template: terraform-apply.yaml
              parameters:
                environment: ${{ parameters.env }}
                location: ${{ parameters.location }}
                stack: ${{ parameters.stack }}
                project: ${{ parameters.project }}
                product: ${{ parameters.product }}
                builtFrom: $(Build.Repository.Name)
                tfversion: ${{ parameters.terraformVersion }}
                serviceConnection: ${{ parameters.environmentServiceConnection }}
                tfStateResourceGroup: ${{ lower(parameters.tfStateResourceGroup) }}
                tfStateStorageAccountName: ${{ lower(parameters.tfStateStorageAccountName) }}
                activity_name: ${{ parameters.activityName  }}
                ${{ if eq(parameters.activityName, 'Video_Hearing_Core') }}:
                  additional_tf_var: $(ado_vars_to_tf.ado_vars)

    - job: ApplyExtToEnv
      displayName: 'Extensions to ${{parameters.env}}'
      dependsOn: Terraform_Apply_${{ parameters.env }}
      steps:
        - template: az-ext-oms.yaml
          parameters:
            subscription: ${{parameters.environmentServiceConnection}}
            vmNames: ["vh-infra-wowza-${{parameters.env}}-0","vh-infra-wowza-${{parameters.env}}-1" ]
            vmRgName:  "vh-infra-wowza-${{parameters.env}}"
            env: ${{ parameters.env }}
            env_long: ${{ variables.env_long }}
        - ${{ if eq(parameters.activityName, 'Video_Hearing_Wowza') }}:
          - ${{ if or(eq(parameters.env, 'stg'), eq(parameters.env, 'prod')) }}:
            - template: az-ext-dynatrace-api.yaml
              parameters:
                subscription: ${{parameters.environmentServiceConnection}}
                vmNames: ["vh-infra-wowza-${{parameters.env}}-0","vh-infra-wowza-${{parameters.env}}-1" ]
                vmRgName: "vh-infra-wowza-${{parameters.env}}"
                env: ${{parameters.env}}
    
    - ${{ if eq(parameters.activityName, 'Video_Hearing_Wowza') }}:
      - job: SqlAccess
        displayName: SQL AD Access 
        dependsOn: Terraform_Apply_${{ parameters.env }}
        steps:
          - template: sql-access.yaml
            parameters:
              azureSubscription: DTS-SHAREDSERVICES-${{ parameters.env }}-Video Hearings
              sqlServerResourceGroup: vh-infra-core-${{ parameters.env }}
              sqlServerName: vh-infra-core-${{ parameters.env }}
              dbAccess:
                - user: 'DTS SDS Developers'
                  databaseNames: 
                    - vhbookings
                    - vhnotification
                    - vhvideo
                  roles:
                    - db_datareader
                    - ${{ if ne(lower(parameters.env), 'prod') }}:
                      - db_datawriter
                - ${{ if eq(lower(parameters.env), 'demo') }}:
                  - user: mi-ingestion-adf-test
                    databaseNames: 
                      - vhbookings
                      - vhnotification
                      - vhvideo
                    roles:
                      - db_datareader
                - ${{ else }}:
                  - user: mi-ingestion-adf-${{ lower(parameters.env)}}
                    databaseNames:
                      - vhbookings
                      - vhnotification
                      - vhvideo
                    roles:
                      - db_datareader